### ISSUE TITLE
Styling - Component Style Approach

### ISSUE THREAD

**Issue by ingrey1** [chingu-voyages/v21-bears-team-04#22]
We need to decide on an approach to styling our React components.

Some possible options:

(1) External .css files for each component
(2) css-as-js (so something like https://formidable.com/open-source/radium/).

Feel free to edit the description and add more options.

Comment below with the approach you prefer.

**Comment by mcchu12** [comment]
I think css-in-js is better for react applications
There are others like [styled component](https://styled-components.com/) and [emotion](https://emotion.sh/docs/introduction)

My personal favorite is [JSS](https://cssinjs.org/react-jss)

**Comment by ingrey1** [comment]
JSS sounds good to me =)
