### ISSUE TITLE
Redux - Decide whether to use an immutable library for reducers

### ISSUE THREAD

**Issue by ingrey1** [chingu-voyages/v21-bears-team-04#25]
So, reducers are supposed to be pure functions - inside the reducers, we shouldn't mutate state. This can make writing reducer logic a pain for deeply nested data structures. One way we could make this easier would be to choose an immutable library.

(1) use no immutable library
(2) use immer (simplest library to use, very popular)
(3) use immutablejs (more to learn to use, also very popular) 

vote as a comment please with your choice, or add an additional choice.

**Comment by mcchu12** [comment]
Let's not use immuatable libs to keep it simple for those who aren't familiar with redux

**Comment by ingrey1** [comment]
Sure, sounds good.
