### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by ingrey1** [chingu-voyages/v21-bears-team-04#30]
So, we're gonna be dealing with a lot of technologies. From what I gather, after reading blogs and what not, besides some smaller startups, testing is big. So, I figure we could decide at least on a general approach. 

(1) We have no tests - we just eyeball things.
(2) We do unit tests. So, for example: models,  utility functions, reducers.
(3) We do unit tests. And then we do some integration / end-to-end tests.
(4) We do a lot of integration testing.

Vote in a comment, please. And feel free to add other options.

**Comment by mcchu12** [comment]
I would suggest unit testing since it is probably the simplest

**Comment by noahniuwa** [comment]
How about unit testing with Jasmine?

**Comment by ingrey1** [comment]
Never used jasmine before, but I'm down to learn =)

**Comment by tcgronk** [comment]
Yep I havent used yet either, but I'm good with that

**Comment by noahniuwa** [comment]
There's also 

https://jestjs.io/
https://www.chaijs.com/
https://mochajs.org/

I know I suggested Jasmine but I am kind of leaning towards Jest right now, Jest has great docs https://jestjs.io/docs/en/getting-started , and it's also the most downloaded of all the packages we suggested on NPM by far https://www.npmjs.com/package/jest  - more than 7 million weekly downloads.
