### ISSUE TITLE
Database - Which Database (and what ORM, if any)

### ISSUE THREAD

**Issue by ingrey1** [chingu-voyages/v21-bears-team-04#5]
* **Decide on a database**
  * SQL or NoSQL? (e.g., mongoDB, postgres)
  * ORM or no ORM? (e.g., write queries in SQL directly, or use a middleman)
    * If we use an ORM, which one (e.g., ActiveRecord, sequelize, sqlAlchemy, mongoose etc.)

**Comment by noahniuwa** [comment]
- Postgresql
- No ORM
