### ISSUE TITLE
Project MVP 

### ISSUE THREAD

**Issue by ingrey1** [chingu-voyages/v21-bears-team-04#7]
* Create The MVP Document
   * fill in details here: https://docs.google.com/document/d/1-0Eb8aXPlnnfKowxewdG1vUO2k-ukRDVdDRv5lWghQQ/edit?usp=sharing

**Comment by noahniuwa** [comment]
- Complete

https://docs.google.com/document/d/1-0Eb8aXPlnnfKowxewdG1vUO2k-ukRDVdDRv5lWghQQ/edit
